### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by edysegura** [HudsonLima/node-restful#3]
I guess it is not expected for you lading page to your logistic provider.

![image](https://cloud.githubusercontent.com/assets/5324414/10886279/632f093e-8168-11e5-9497-44e95239589b.png)

**Comment by HudsonLima** [comment]
Edy, its not running. When you be ready tall me and I will make a NPM start at server.

**Comment by edysegura** [comment]
I could access now! Thank you!

**Comment by HudsonLima** [comment]
Hello, @edysegura! What Url did u acess? 
The server is offline. I Turned it down 3 days ago coz AWS were billing me. 

Hugs,

**Comment by edysegura** [comment]
I was using hudsonlima.tk! As you sent.

**Comment by HudsonLima** [comment]
@edysegura but the server wasn`t online. You can check it now, I just started the instance again.
hudsonlima.tk for swagger and hudsonlima.tk/api/entrega for api

![start time](https://cloud.githubusercontent.com/assets/5431216/11032081/0673bf16-86c0-11e5-88ad-315cecc7e3c3.png)

**Comment by edysegura** [comment]
It was okay! I have checked you project offline! Thank you for your attention.

**Comment by HudsonLima** [comment]
@edysegura sorry? I could not understand what you just wrote... It is offline because after no response from you I stopped the server at 09-11 5 hours +/- after start time.

I am not able to keep service online full time coz it costs money and I`m not that rich 

Anyway, I just made 'npm start' once again and I will keep it online again during the morning.

As you can see, here it goes the screen. 

(please let me know if you read the mesage)

Thanks in advance

![postman](https://cloud.githubusercontent.com/assets/5431216/11180621/4daa8a44-8c43-11e5-8837-e31ee0007fc2.png)

**Comment by edysegura** [comment]
I have installed it in my own machine. That's mean I could check your
homework offline.

Please turn off your machine.

Cheers,
Edy Segura

**Comment by HudsonLima** [comment]
Oh okay @edysegura 
I let online again to make sure you checked that I reached the topic "online deploy" 
By the way, I hope you have been able to see the report relatorio.php also in your local machine

I`m going to stop my machine now.

Thanks,
Hudson
